#ifndef __GLOBAL_GAME_H__
#define __GLOBAL_GAME_H__


typedef enum _GAME_STATE
{
	GS_UNDEFINED = 0,
	GS_GAME = 1,
	GS_HELP = 2,
	GS_OPTIONS = 3,
	GS_REGISTRATION = 4,
	GS_MODALDLG = 5
}GAME_STATE;


const BYTE EDIT_SIZE = 21;
const BYTE DSIZE = 4;

//defined states id
#define ES_PAD_CLOSEHELP ES_USERSTATE + 1
#define ES_PAD_RESTORECURSOR ES_USERSTATE+2

#define ES_OPTIONS_OPEN ES_USERSTATE + 20
#define ES_OPTIONS_CLOSE ES_USERSTATE + 21

#define ES_DLGNAG_INIT ES_USERSTATE + 40

#define ES_ENGINE_CHECKMUSIC ES_USERSTATE + 50

#define L_UNNAMED "UNNAMED"

#endif //__GLOBAL_GAME_H__